export {default as AllProducts} from './AllProducts'
export {default as Smartphones} from './Smartphones'
export {default as Laptops} from './Laptops'
export {default as ProductPage} from './ProductPage'
export {default as CartPage} from './CartPage'
export {default as Page404} from './Page404'